
services:
  go-app:
    container_name: go-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    restart: on-failure
    environment:
      - TODO_DB_DSN=postgresql://postgres:postgres@db:5432/todo?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: db
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5